name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    - name: SSH and deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.EC2_PROJECT_PATH }}

          # Pull latest code
          git pull origin main

          # Activate virtualenv
          source venv/bin/activate || python3 -m venv venv && source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Run your app (customize this)
          nohup python3 main.py > app.log 2>&1 &
        EOF
