name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy via SSH to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e
            echo "🧹 Cleaning up old temp directory..."
            rm -rf /home/ubuntu/backend-temp || true
            mkdir -p /home/ubuntu/backend-temp

            echo "📥 Cloning latest repo..."
            git clone git@github.com:${{ github.repository }} /home/ubuntu/backend-temp

            echo "🔐 Creating .env file..."
            cat <<EOF > /home/ubuntu/backend-temp/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}
            RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}
            EOF

            echo "🧼 Cleaning existing deployment directory..."
            rm -rf /home/ubuntu/backend-app/*

            echo "🚚 Moving build to deployment directory..."
            mv /home/ubuntu/backend-temp/* /home/ubuntu/backend-app/

            echo "📦 Deploying app"
            cd /home/ubuntu/backend-app
            chmod +x setup.sh
            ./setup.sh
